-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-1", mode = "1920x1080@143.981", position = "1920x300", scale = 1, transform = 1, vrr = 1 })
hl.monitor({ output = "DP-2", mode = "2560x1440@239.958", position = "3002x714", scale = 1, vrr = 1, bitdepth = 10 })
